.\" Manpage for RateMyProfessors.help.
.\" Contact duy.yuuwe@pm.me to correct errors or typos.
.TH man 8 "26 Aug 2022" "0.1" "rmp man page"
.SH NAME
rmp \- host RateMyProfessors.help webserver
.SH SYNOPSIS
rmp
.SH DESCRIPTION
hosts webserver
.SH OPTIONS
The rmp does not take any options. 
.SH SEE ALSO
httpd(8), httpd.conf(5), relayd(8), relayd.conf(5), acme-client(1), acme-client.conf(5), postgres(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Duy Nguyen (duy.yuuwe@pm.me)
