#!/usr/bin/env/ python3
'''
this script needs to be worked on for later
departments were generated by
1. downloading html
2. using vim select
3. awk to remove unnecessary parts
'''

import requests
from bs4 import BeautifulSoup

departments=requests.get('https://www.deanza.edu/schedule/')

soup = BeautifulSoup(departments.content,'html.parser')

select = soup.find(id='dept-select')

for option in select.find_all('option'):
    print(option)

