#!/bin/ksh

dir="/var/rmp/RateMyProfessors.help"
daemon="${dir}/webserver"
daemon_flags=
daemon_user="_rmp"

. /etc/rc.d/rc.subr

rc_bg=YES
#rc_reload=NO

# su -fl -c ... look at man rc.d.subr and the template file
rc_start() {
  ${rcexec} "cd ${dir} && ${daemon} ${daemon_flags}"
}

rc_cmd $1
