#!/bin/ksh

daemon="/home/yuuwe/RateMyProfessors.help/webserver"
daemon_flags=""
daemon_user="yuuwe"

. /etc/rc.d/rc.subr

#rc_bg=YES
#rc_reload=NO

rc_start() {
	${rcexec} "${daemon} ${daemon_flags} 2>&1 | logger -t $(daemon) &"
}

rc_cmd $1
