name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      -
        name: Build the Docker image
        run: |
          DATE="$(date +%s)"
          docker build . --file Dockerfile --tag danknessdra/ratemyprofessors.help:"$DATE"
          docker push danknessdra/ratemyprofessors.help:"$DATE"
