name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - run: date=$(date +%s)
    - run: docker build . --file Dockerfile --tag danknessdra/ratemyprofessors.help:"$(date)"
      #    - run: docker push danknessdra/ratemyprofessors.help:"$(date)"
